#!/usr/bin/env python3
"""
AI Code Reviewer - Few-Shot Prompt Optimizer

Reads the telemetry dataset (`backend/data/telemetry.jsonl`) generated by users resolving AI comments,
extracts the best examples, and formulates a few-shot learning prompt file to fine-tune the AI's behavior.
"""
import os
import json
import argparse
from typing import List, Dict

def main():
    parser = argparse.ArgumentParser(description="Optimize AI Prompt using Telemetry")
    parser.add_argument("--telemetry-file", type=str, default="../../backend/data/telemetry.jsonl", help="Path to telemetry.jsonl")
    parser.add_argument("--output", type=str, default="../few_shot_prompt.md", help="Output prompt file")
    args = parser.parse_args()

    telemetry_path = os.path.abspath(os.path.join(os.path.dirname(__file__), args.telemetry_file))
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), args.output))

    if not os.path.exists(telemetry_path):
        print(f"⚠️ Telemetry file not found at {telemetry_path}. Generating an empty few-shot prompt.")
        with open(output_path, 'w') as f:
            f.write("")
        return

    examples: List[Dict] = []
    with open(telemetry_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
                if data.get('action') == 'resolved' and data.get('ai_comment') and data.get('diff_hunk'):
                    examples.append(data)
            except json.JSONDecodeError:
                pass

    if not examples:
        print("ℹ️ No resolved examples found in telemetry.")
        return

    # In a real scenario, we might use embeddings to deduplicate or score examples by upvotes.
    # For now, we take the most recent 5 accepted reviews to keep the prompt context short.
    top_examples = examples[-5:]

    prompt_content = "### Few-Shot Examples (Team Preferences)\n\n"
    prompt_content += "The following are highly-rated examples of code reviews that align with this team's expectations. Use these as a style and strictness guide:\n\n"

    for i, ex in enumerate(top_examples, 1):
        prompt_content += f"#### Example {i}\n"
        prompt_content += f"**Code Snippet:**\n```diff\n{ex['diff_hunk']}\n```\n\n"
        prompt_content += f"**Ideal AI Review:**\n{ex['ai_comment']}\n\n"
        prompt_content += "---\n\n"

    with open(output_path, 'w') as f:
        f.write(prompt_content)

    print(f"✅ Extracted {len(top_examples)} high-quality examples into {output_path}")

if __name__ == "__main__":
    main()
